[build]
  functions = "src/functions"
  command = "next build && next export"
  publish = "out"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "@netlify/plugin-nextjs"
