[build]
  functions = "src/functions",
  publish = ".next"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "netlify-plugin-cache-nextjs",
  package = "@netlify/plugin-nextjs"
