backend:
	name: git-gateway
	branch: master
  media_folder: static/img
  slug:
	encoding: 'ascii'
	clean_accents: true
	sanitize_replacement: '_'
  collections:
	- name: 'treatments'
	  label: 'Treatments'
	  files:
		  file: 'content/treatments.md'
		  fields:
			- { label: 'Treatment', name: 'treatment', widget: 'string' }
			- { label: 'Blurb', name: 'blurb', widget: 'markdown' }
			- { label: 'Price', name: 'price', widget: 'string' }
			- { label: 'Publish Date', name: 'date', widget: 'datetime' }

  